### PR TITLE
ci: test ci pr

### PR DESCRIPTION
**Pull request by yuluo-yx**

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
I don't know if it will retrigger all related Actions or only the failed actions.

**Comment by yuluo-yx** [comment]
> I don't know if it will retrigger all related Actions or only the failed actions.

He will just collect the job that failed to run and rerun this task, I seem to have found something wrong, I will fix it! 
You can view the actions of this repository after typing the command /retest: https://github.com/yuluo-yx/deigmata-paideias/actions.

**Comment by LinuxSuRen** [comment]
Yes, I saw the running actions. Please let me know if you believe the Action is ready to go.

**Pull request closed without merging**
